project:
  type: website
  output-dir: docs
  # resources: 
    # - "_xaringan_slides/lecture01/*" # can add resources / pre-built pages. Needs testing!
    # - "_xaringan_slides/lecture01/img/*"

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "BIOS-338/538"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/slides.qmd
        text: Lecture slides
  repo-url: https://github.com/BIOS-538.github.io # links to github
  repo-actions: [edit, issue]  
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



