project:
  type: website
  output-dir: docs
  resources:
    - "slides/scripts/*.R"
    - "slides/lecture04_tidyverse_intro.pptx"
    - "slides/assets/lec04_tidyverse_intro_worksheet.docx"
    # - "_xaringan_slides/lecture01/*" # can add resources / pre-built pages. Needs testing!
    # - "_xaringan_slides/lecture01/img/*"

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "BIOS-338/538"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/class_schedule.qmd
        text: Class schedule & Lecture slides
  repo-url: https://github.com/BIOS-538.github.io # links to github
  repo-actions: [edit, issue]
  page-footer: 
    left: "Copyright 2024, Prashant Kalvapalle"
    right:
      - text: "Creative commons license. CC-BY-4.0"
        href: LICENSE-CC-BY-4.0.md
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



