---
title: "Class schedule & Lecture slides"
execute:
  freeze: false # always execute the R code
editor: visual
---

Below is a general description of the material to be covered. *Note that topics and dates are\
subject to change as the course progresses*.

```{r}
#| label: render-table
#| echo: false
options(knitr.kable.NA = "")

# Load schedule from the spreadsheet
sch <- readODS::read_ods('assets/class_schedule.ods') #%>% 

# Render table: Key = hyperlinks
knitr::kable(sch, format = 'pipe')

# another function for grid_tables: show's raw code, not rendering html :(
# pander::pandoc.table(sch, style = 'rmarkdown')

```

### How do I download the slides as PDF for writing notes?

If you would like to download and write notes on the slides as PDFs, you can do it with this procedure

1.  When the slide show is open in the browser, click on `e` to change to `PDF export mode`
2.  Now press `ctrl` + `P` key combination to print the page and select PDF, and you are good to go!

If you want your annotations to stay current when the slides are edited, you might want to annotate within the web version of slides itself. You can use tools such as hypothes.is for this. This link should help you get setup - <https://web.hypothes.is/start/>

You could do more drawing on the pages too if you use the edge browser as show on this page: [Write on the web](https://support.microsoft.com/en-us/windows/write-on-the-web-8743d2bb-c4cf-ae40-2aa2-a88ae96a4a79)
